### ISSUE TITLE
カウンター及びそれを拡張したシンボルの定義

### ISSUE THREAD

**Issue by kerochan** [scp-tcg-jp-j/rule#1]
Wiki版STJJのカードにはカウンターがよく見られますが、これに関するルールが明記されていません。

**Comment by smctrl** [comment]
カードやサンドボックスやプレイヤーに何らかの状態を持たせるルールが必要という理解で合っていますか？  
このあたりのルールが整備されると『「第五主義」を得る』も明確にルールで解釈できるようになるのでいいと思います。

**Comment by kerochan** [comment]
そのような認識で問題ありません。
