### ISSUE TITLE
架空のタグについて

### ISSUE THREAD

**Issue by smctrl** [scp-tcg-jp-j/rule#16]
[開発中のルールのタグの説明](https://github.com/scp-tcg-jp-j/rule/blob/develop/rule/%E3%82%AB%E3%83%BC%E3%83%89/%E8%A6%81%E7%B4%A0/%E3%82%BF%E3%82%B0.md) を見る限り、日本支部や財団本部、またはその他の支部にも存在しない架空のタグをゲーム中で用いることが可能なように思えますが、可能という考えで合っていますか？  
そういうことをする人はいないと思いますし、いたとしても実害はないとは思いますが、一応聞いてみました。

**Comment by kerochan** [comment]
はい、可能です。おっしゃる通り、SCP財団で用いられていないタグを使用するメリット・デメリットはあまりないとは思います。そのため存在しないタグでも使用可能なようになっています。

**Comment by smctrl** [comment]
了解しました。ありがとうございます
